### ISSUE TITLE
All moons in Course of the Day

### ISSUE THREAD

**Issue by MichaelMcDonnell** [SecUSo/privacy-friendly-weather#131] opened 2020-09-03 17:52 UTC
The Course of the Day is showing all moons in the latest master 7119a33c2b38321c5355d9c37cb454005ae12839. It shows moons for both the day and night. I'm in California so I think it is related to the recent changes to use timezone corrected times.

![Screenshot_1599155494](https://user-images.githubusercontent.com/20253/92149865-7381f300-edd3-11ea-950f-0889f4151bf8.png)

**Comment by MichaelMcDonnell** [comment] 2020-09-03 19:49
Hey @woheller69 and @sleep-yearning, I bisected this issue and it is caused by commit 869183946ccfb500075f71a51a82bdd910502783.

**Comment by woheller69** [comment] 2020-09-03 20:31
On my work-branch2 which has not yet been merged it works fine. Also checked with Los Angeles timezone. So I guess it is a problem from merging with other changes on master.

**Comment by woheller69** [comment] 2020-09-03 20:54
The forecastTime and sunSetTime stuff was not part of my original commit. Probably the problem is somewhere there...
I have seen that sleep-yearning was working on changing my fix 5am to 8pm definition for "day" to a definition based on sunrise and sunset.

**Comment by woheller69** [comment] 2020-09-04 04:20
I think what needs to be done is the following. Sunset/Sunrise are taken from current weather and are available only for current day. We assume these times do not strongly change for the next days. Then, in analogy to the bugfix for day/night icon, isDay should be true if local(!)ForecastTime is between sunrise/sunset or between (sunset+24h)/(sunrise+24h) or between ....(...+72h/ +72h). I don't think calculations with calendar are needed. Right?

**Comment by sleep-yearning** [comment] 2020-09-06 16:20
It might have been a dumb mistake by me. I thought I could simplify the comparison, taking timezone out of the equation, but the values are used elsewhere too. Im closing with the reverting commit, please reopen if that wasn't the only issue. 
Regarding the day issue: I already set the day of year as the same for all the comparison values, so that shouldn't be the problem. (seems to work)

**Closed** 2020-09-06 19:59 UTC
