### ISSUE TITLE
Widget never updates

### ISSUE THREAD

**Issue by stemy2** [SecUSo/privacy-friendly-weather#130] opened 2020-09-03 10:27 UTC
Hello,

Once i put the widget on the main screen, it shows the actual weather/forecast, but then, it never updates. I still have the weather/forecast from yesterday.

**Comment by sleep-yearning** [comment] 2020-09-03 13:33
The automatic update is not working as intended right now.
If you click the update button in the app (or just open the app, depending on your update interval set in settings),
It will also update the widgets.

**Comment by stemy2** [comment] 2020-09-03 13:35
> The automatic update is not working as intended right now.
> If you click the update button in the app (or just open the app, depending on your update interval set in settings),
> It will also update the widgets.

Nope, the widget stills not update even when i'm doing this.

**Comment by sleep-yearning** [comment] 2020-09-03 13:43
Sorry, my bad. The released version in the PlayStore/F-Droid doesn't have this workaround yet.

**Comment by stemy2** [comment] 2020-09-03 13:53
So where is the version where the workaround works ? I see that the version released on github is the same as the one released in the stores.

**Comment by sleep-yearning** [comment] 2020-09-06 15:54
Unfortunately we didn't make a new release yet. There are a few bugfixes and features which have to be done first.

**Comment by woheller69** [comment] 2020-10-05 07:57
For me it does not work either and my fork is not too old. When I click on the widget it opens the app and the data is updated and shown correctly in the app. But the widget remains unchanged.

**Comment by sleep-yearning** [comment] 2021-01-14 12:09
This should be resolved by now. Feel free to reopen if not.

**Closed by sleep-yearning** 2021-01-14 12:09 UTC

**Comment by woheller69** [comment] 2021-01-17 07:38
I don´t think it works. The widget only updates if you open the app and update the city there. 
If you just switch on the phones screen and watch the widget it never changes.
But then I don´t need a widget...
