### ISSUE TITLE
Android widget shows dummy values for certain towns

### ISSUE THREAD

**Issue by jelmerdus** [SecUSo/privacy-friendly-weather#82] opened 2019-06-07 18:18 UTC
When launching the 3 or 5 day andoid widget for Oss (NL), it shows "CityName" instead of Oss and dummy values for temperature and humidity. Oss works fine in the all though.

**Comment by Bug-Ninja** [comment] 2019-10-10 10:18
Experiencing the same thing here. The widget with today's info is working. The app asks me to enter the city,but the widget is not updated with it.
I tried deleting user data and cache of the app, but it does not help. 

Running Lineageos 15.1 on nexus 5x.

**Comment by petermayer** [comment] 2020-01-30 14:49
Duplicate of #67

**Closed** 2020-01-30 14:49 UTC
Labels: bug
